# Generated by Django 5.0.6 on 2024-06-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='pdf',
        ),
    ]
