# Generated by Django 5.0.6 on 2024-06-03 10:54

import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CS', 'CS'), ('CSE(AIML)', 'CSE-AIML'), ('CSE(DS)', 'CSE-DS'), ('CSE(Hindi)', 'CS(Hindi)'), ('AIML', 'AIML'), ('IT', 'IT'), ('CSIT', 'CS&IT'), ('ECE', 'ECE'), ('EN', 'EN'), ('ME', 'ME'), ('CIVIL', 'CE')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='student_no',
            field=models.IntegerField(default=0, unique=True, validators=[user.models.validate_Student_digits]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('staff', 'Staff'), ('student', 'Student')], max_length=15),
        ),
    ]
