# Generated by Django 5.0.6 on 2024-06-03 13:16

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_branch_alter_user_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True,  validators=[user.models.validate_akgec_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_no',
            field=models.IntegerField(null=True, unique=True, validators=[user.models.validate_Student_digits]),
        ),
    ]
