# Generated by Django 5.0.6 on 2024-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email_alter_user_student_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
