# Generated by Django 5.0.6 on 2024-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_branch_alter_user_student_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'administrator'), ('staff', 'staff'), ('student', 'student')], max_length=15),
        ),
    ]
